#pragma once
#ifndef SE_CALLBACKS_H
#define SE_CALLBACKS_H

#include "SE_Types.h"

struct SE_SEARCHCONTEXTSTORAGE;
struct SE_NODE;

typedef void (*SE_FN_ONFSMCOMPLETE)(SE_EXECUTIONTOKEN, SE_SEARCHCONTEXTSTORAGE*, SE_THREAD*);
typedef void(*SE_FN_AGGREGATECONTEXT)(SE_NODE*, SE_SEARCHCONTEXTSTORAGE*);

struct SE_CALLBACKS
{
	SE_FN_ONFSMCOMPLETE OnFsmComplete;
	SE_FN_AGGREGATECONTEXT OnAggregateSearchContext;
};

void CALLBACKS_Initialize(SE_CALLBACKS* pCallbacks, SE_FN_ONFSMCOMPLETE onFsmComplete);

#endif