#pragma once
#ifndef MG_PIECEINFO_H
#define MG_PIECEINFO_H

#include "MG_MOVEMECHANIC.h"
#include "MG_MOVETYPE.h"
#include "MG_PIECETYPE.h"

#define COUNT_TABLEINDICES (COUNT_PIECETYPES+2)
#define TABLEINDEX_QUIET 0
#define TABLEINDEX_SPECIAL 1
#define TABLEINDEX_CAPTURE(_PIECE_) (2+(_PIECE_))

typedef std::int8_t MG_TABLEINDEX;

struct MG_PIECEINFO
{
	bool IsRoyal;
	MG_MOVEMECHANIC MoveMechanic[COUNT_MOVETYPES];
	MG_TABLEINDEX TableIndex[COUNT_TABLEINDICES];
};

#endif